import localFont from "next/font/local";
import "../globals.css";
import NewScheduleModal from "@/components/modals/newScheduleModal";
import NewDisciplineModal from "@/components/modals/newDisciplineModal";
import { Toaster } from "react-hot-toast";
import TeamDetailsModalData from "@/components/modals/teamDetailsModal";
import AthleteDetailsModal from "@/components/modals/athleteDetailsModal";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Olympic Games",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <TeamDetailsModalData />
      <AthleteDetailsModal />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-full h-[100vh] flex flex-col">
          <header className="bg-slate-700 sticky top-0 z-50">
            <div className="container relativer m-auto flex items-center justify-between min-h-28">
              <a className="text-4xl font-paris text-white cursor-pointer" href="/" >
                Olympic Games 2024
              </a>
              <img className="w-20 absolute left-1/2 -translate-x-1/2" src="https://olympics.com/_pr/topic-assets/paris-2024/emblem-oly.svg" />
              <img className="w-20" src="	https://olympics.com/images/static/b2p-images/logo_color.svg" />
            </div>
            {<div className="container m-auto">
              <nav className="flex space-x-4 h-10 justify-center items-center">
                <a href="/schedules" className="text-white hover:tracking-wider duration-300 px-4 box-border">Schedules</a>
                <a href="/disciplines" className="text-white hover:tracking-wider duration-300 px-4 box-border">Disciplines</a>
                <a href="/events" className="text-white hover:tracking-wider duration-300 px-4 box-border">Events</a>
                <a href="/countries" className="text-white hover:tracking-wider duration-300 px-4 box-border">Countries</a>
                <a href="/athletes" className="text-white hover:tracking-wider duration-300 px-4 box-border">Athletes</a>
                <a href="/coaches" className="text-white hover:tracking-wider duration-300 px-4 box-border">Coaches</a>
                <a href="/medallists" className="text-white hover:tracking-wider duration-300 px-4 box-border">Medals</a>
                <a href="/teams" className="text-white hover:tracking-wider duration-300 px-4 box-border">Teams</a>
              </nav>
            </div>}
          </header>
          {children}
        </div>
      </body>
    </html>
  );
}
